webform_as_block.settings:
  type: config_object
  label: 'Webform blocks settings'
  mapping:
    webform_list:
      type: sequence
      label: 'Available wobforms'
      sequence:
        type: string
        label: 'Availability'
